### ISSUE TITLE
Wrong behaviour UIInput's component

### ISSUE THREAD

**Issue by samsonovav** [wildfly/mojarra#71]
After upgrading to wildfly 19.1.0 my projects don't work as expected.
I localized problem in javax.faces.component.UIInput from jboss-jsf-api_2.3_spec 3.0.0.SP02 in validate(FacesContext context) method. When the context parameter javax.faces.INTERPRET_EMPTY_STRING_SUBMITTED_VALUES_AS_NULL set to true then the value from UIInput component is not set to null any more. Moreover, the setter method on backing bean is not called in this case. I write here because the https://github.com/jboss/jboss-jakarta-faces-api don't have the place for issues.

**Comment by erickdeoliveiraleal** [comment]
you might want to open the issue also in root project that is https://github.com/eclipse-ee4j/mojarra , this bug may related to the fix of this issue https://github.com/eclipse-ee4j/mojarra/issues/4550

**Comment by scottmarlow** [comment]
> you might want to open the issue also in root project that is https://github.com/eclipse-ee4j/mojarra , this bug may related to the fix of this issue eclipse-ee4j/mojarra#4550

I agree, +100

**Comment by scottmarlow** [comment]
Also worth adding a link to the discussion forum as well, in case further notes are added there, [link is](https://groups.google.com/d/msgid/wildfly/9ae153b7-0525-42ec-ba57-c28f9305d452%40googlegroups.com?utm_medium=email&utm_source=footer).

**Comment by samsonovav** [comment]
Ok. Thanks.
I submitted issue to https://github.com/eclipse-ee4j/mojarra/issues/4704

**Comment by erickdeoliveiraleal** [comment]
@soul2zimate

**Comment by Hurz** [comment]
The fix has caused a new misbehaviour: When rendering a composit component with a facet containing a required input field, its validation triggers even though the field isn't rendered.

I've attached a reproducer to its Mojarra bug ticket https://github.com/eclipse-ee4j/mojarra/issues/4704 .

**Comment by soul2zimate** [comment]
It's the same issue as described in https://github.com/eclipse-ee4j/mojarra/issues/4716, it was fixed in https://issues.redhat.com/browse/WFLY-13497
