### ISSUE TITLE
Release 2.3.9.SP09

### ISSUE THREAD

**Issue by bunckelvhv** [wildfly/mojarra#74]
Hello Farah @fjuma 

could you please be so kind to release JBoss Mojarra 2.3.9.SP09?
https://github.com/jboss/mojarra/tree/2.3.9.SP09

It's not visible in the public repo:
https://mvnrepository.com/artifact/com.sun.faces/jsf-impl?repo=jboss-public

We need it urgently due to the security fixing it contains.

Thanks in advance

Kind regards
Boris

**Comment by fjuma** [comment]
@bunckelvhv JBoss Mojarra 2.3.9.SP09 was already released in April. It's available in the public repo already:

https://mvnrepository.com/artifact/com.sun.faces/jsf-impl/2.3.9.SP09

**Comment by bunckelvhv** [comment]
Thank you, wondering why it is not listed in the global list.

**Comment by bunckelvhv** [comment]
@fjuma Yes, I have found the impl - working.
But this namespace is missing the update:
https://mvnrepository.com/artifact/org.jboss.spec.javax.faces/jboss-jsf-api_2.3_spec

**Comment by fjuma** [comment]
The corresponding API JAR is here:

https://mvnrepository.com/artifact/org.jboss.spec.javax.faces/jboss-jsf-api_2.3_spec/3.0.0.SP02

**Comment by bunckelvhv** [comment]
Thank you very much! It helps a lot.
