### ISSUE TITLE
Merge pull request #4727 from eclipse-ee4j/mojarra

### ISSUE THREAD

**Issue by erickdeoliveiraleal** [wildfly/mojarra#77]
@melloware opened a issue and sent a pull request to main repository, please merge it here too. thanks.
> While adding Client Window ID support to PrimeFaces a bug in Mojarra was discovered.
> See: primefaces/primefaces#6030
> 
> Basically Mojarra is building an incorrect URL for ClientWindowID like the screenshot below:
> https://user-images.githubusercontent.com/10461942/85319612-10fea380-b4c2-11ea-8373-3d25a025ea05.png
> 
> This issue is right here:
> 
> mojarra/impl/src/main/java/com/sun/faces/context/UrlBuilder.java
> 
> Line 242 in 2d22f78
> 
>  url.append(PARAMETER_NAME_VALUE_SEPARATOR); 
> I will be submitting a PR to fix it.

**Comment by melloware** [comment]
PR is here: https://github.com/eclipse-ee4j/mojarra/pull/4728
