### ISSUE TITLE
Modifications for running the mojarra test-suite with wildfly

### ISSUE THREAD

**Issue by rmartinc** [wildfly/mojarra#80]
The idea is running the TS that mojarra upstream project executes when a PR is sent, but using wildfly instead of glassfish. For example this [travis page](https://travis-ci.org/github/eclipse-ee4j/mojarra/builds/608301704) shows the results from an old PR sent to the upstream project. The TS is run for the following groups:

* test/htmlunitaware
* test/javaee6
* test/javaee6web
* test/javaee7
* test/javaee8
* test/servlet31
* test/servlet40

The servlet30 folder is also executed OK for glassfish (lots of tests there).

**Comment by rmartinc** [comment]
Summary of issues with the TS:

* **javaee6**:
  * **correctScanningEar**: the problem here is that a JAR contains a faces-config.xml and it's buncled in the EAR/lib shared folder. It seems that [this is not OK](https://stackoverflow.com/questions/30535024/facescomponent-on-shared-library/) and it should be moved to WEB-INF/lib.
  * **resource/cacheLastMod**: The EAR and WAR application are deployed with the same. In wildfly it fails with duplicate app error (the "-war" suffix was added to the the WAR app).
* **javaee6web**:
  * **injectArtifacts** (and others): [WFLY-13754](https://issues.redhat.com/browse/WFLY-13754)
  * **flowAndTemplateUsingJar**: a persistence.xml leftover makes the app deployment fail.
* **javaee8**:
  * **el**: The test checks that #{application} returns string "Application" which is glassfish specific. Changed to test that the application is a ServletContext as spec says.
  * **cdi**: [WFLY-14018](https://issues.redhat.com/browse/WFLY-14018). In 2.3.9.SP branch a messages is also needed for issue4551 (in 2.3.14.SP is there).
* **servlet30**:
  * **client_encrypt_by_default**: it uses IDs for testing, in wildfly a different number is assigned. Just changed to locate the input by name.
  * **customFaceletsResolver/faceletResourceResolver2**: new issue in wildfly (a new JIRA needed). [WFLY-14238](https://issues.redhat.com/browse/WFLY-14238) filed.
  * **multiTenantSetsTccl**: wildfly initializes servlet filters lazily by default (not in the spec). Just needed to change that behavior: `/subsystem=undertow/servlet-container=default:write-attribute(name=eager-filter-initialization, value=true)`.
  * **navigation2**: The test checks for ApplicationImpl but in wildfly it's org.jboss.as.jsf.injection.weld.WeldApplication, so just checks for the interface Application.
  * **nestedLoadBundles**: The test uses c:import to import several JSPs, but it needs f:subview or use f:verbatim as explained [here](https://www.infoworld.com/article/2073098/getting-around-jsf--the-role-of-jsp.html).
  * **neverUnwrapExceptions**: It checks specific exceptions that are different in wildfly (test excluded from the parent servlet30).
  * **systest**: This is a pity, the test works OK but the package used is con.sun.faces.systest which is excluded in the wildfly implementation. Previously [this commit](https://github.com/wildfly/wildfly/pull/13479/files#diff-d4670ab83503285c537bb8ccabce98d621b9a1256f7e1526e2185ddf53c65799L58) allowed the test-suite classes but this test uses a different package. Test also excluded from parent servlet30.

**Comment by rmartinc** [comment]
PRs sent for both branches:
  * 2.3.9.SP: https://github.com/jboss/mojarra/pull/81
  * 2.3.14.SP: https://github.com/jboss/mojarra/pull/82

**Comment by rmartinc** [comment]
@fjuma Do we close this as it's merged?
Thanks!

**Comment by fjuma** [comment]
Thanks, @rmartinc, I'll close this.
